# Introduction

## Import NumPy

In [3]:
import numpy

array = numpy.array([1, 2, 3, 4, 5])

print(array)

[1 2 3 4 5]


In [13]:
from numpy import array

arr = array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Checking version

In [27]:
print(np.__version__)

1.26.4


# Creating arrays

In [35]:
arr_tuple = np.array((-1, 0, 1)) # tuple
arr_list = np.array([-1, 0, 1]) # list

print(arr_tuple)
print(arr_list)

[-1  0  1]
[-1  0  1]


In [37]:
print(type(arr))

<class 'numpy.ndarray'>


### Tensor -- N-Dimesional numeric array

0D array - Scalar

1D array - Vector

2D array - Matrix

3D array - Tesor (Stack of matrices)

ND+ array - Nnd order tensor

### Datatype


In [57]:
arr_float = np.array((1.1, 0, -23.0))
arr_int = np.array((1, 35, 0, -43))

# dtype - data type, attribute of class `numpy.ndarray`
print(arr_float.dtype)
print(arr_int.dtype)

float64
int32


## Dimesions in arrays

In [3]:
arr_0d = np.array(10)

print(arr_0d)

10


In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d)

[1 2 3 4 5]


In [9]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Number of dimensions


In [16]:
print(arr_0d.ndim)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

0
1
2
3


In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


## Indexing

In [3]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [5]:
print(arr[1])

2


In [7]:
print(arr[2] + arr[3])

7


In [47]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [17]:
print(arr, end='\n\n')
print(arr[0], end='\n\n')
print(arr[0, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[1 2 3 4 5]

5


In [19]:
print(arr[1, 4])

10


In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 1, 0])

10


In [27]:
print(arr[-2, -3])

3


## Slicing

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [32]:
print(arr[:4])

[1 2 3 4]


In [34]:
print(arr[-3:-1])

[5 6]


In [38]:
print(arr[-1:1:-1])

[7 6 5 4 3]


In [42]:
print(arr[1:5:2])

[2 4]


In [45]:
print(arr[::2])

[1 3 5 7]


In [49]:
print(arr[1, 1:4])

[7 8 9]


In [51]:
print(arr[:2, 2])

[3 8]


In [53]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Data Types

In [3]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [13]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6
