# Introduction

## Import NumPy

In [3]:
import numpy

array = numpy.array([1, 2, 3, 4, 5])

print(array)

[1 2 3 4 5]


In [13]:
from numpy import array

arr = array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Checking version

In [27]:
print(np.__version__)

1.26.4


# Creating arrays

In [35]:
arr_tuple = np.array((-1, 0, 1)) # tuple
arr_list = np.array([-1, 0, 1]) # list

print(arr_tuple)
print(arr_list)

[-1  0  1]
[-1  0  1]


In [37]:
print(type(arr))

<class 'numpy.ndarray'>


### Tensor -- N-Dimesional numeric array

0D array - Scalar

1D array - Vector

2D array - Matrix

3D array - Tesor (Stack of matrices)

ND+ array - Nnd order tensor

### Datatype


In [57]:
arr_float = np.array((1.1, 0, -23.0))
arr_int = np.array((1, 35, 0, -43))

# dtype - data type, attribute of class `numpy.ndarray`
print(arr_float.dtype)
print(arr_int.dtype)

float64
int32


## Dimesions in arrays